---
- name: Converge
  hosts: all
  become: true

  tasks:

    - name: "Include grycap.hadoop"
      include_role:
        name: "ansible-role-hadoop"
      vars:
        hadoop_master: "hadoopmaster"
